config/routes.rb
# == Route Map
#
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root to: 'home#index'
  get 'flats_catalog', to: 'flats_catalog#index'
  get 'country_side_houses_catalog', to: 'country_side_houses_catalog#index'
  get 'commercial_premises_catalog', to: 'commercial_premises_catalog#index'
  get 'admin_panel', to: 'admin_panel#index'
  scope '/reports' do
    get 'users-count', to: 'reports#users_count'
    post 'users_count_report', to: 'reports#users_count_report'
    get 'clients-count', to: 'reports#clients_count'
    post 'clients_count_report', to: 'reports#clients_count_report'
    get 'realtors-count', to: 'reports#realtors_count'
    post 'realtors_count_report', to: 'reports#realtors_count_report'
    get 'locked-users-count', to: 'reports#locked_users_count'
    post 'locked_users_count_report', to: 'reports#locked_users_count_report'
    get 'lots-count', to: 'reports#lots_count'
    post 'lots_count_report', to: 'reports#lots_count_report'
    get 'commercial-premises-count', to: 'reports#commercial_premises_count'
    post 'commercial_premises_count_report', to: 'reports#commercial_premises_count_report'
    get 'country-side-houses-count', to: 'reports#country_side_houses_count'
    post 'country_side_houses_count_report', to: 'reports#country_side_houses_count_report'
    get 'flats-count', to: 'reports#flats_count'
    post 'flats_count_report', to: 'reports#flats_count_report'
    get 'not-started-lots-count', to: 'reports#not_started_lots_count'
    post 'not_started_lots_count_report', to: 'reports#not_started_lots_count_report'
    get 'published-lots-count', to: 'reports#published_lots_count'
    post 'published_lots_count_report', to: 'reports#published_lots_count_report'
    get 'completed-lots-count', to: 'reports#completed_lots_count'
    post 'completed_lots_count_report', to: 'reports#completed_lots_count_report'
  end
  resources :ordering
  resources :deal_types
  resources :countries
  resources :property_types
  resources :ready_states
  resources :country_side_house_kinds
  resources :commercial_premises_kinds
  resources :renovations
  resources :wall_materials
  resources :lots
  resources :country_side_houses do
    collection do
      put 'remove_from_work', to: 'country_side_houses#remove_from_work'
      put 'publish', to: 'country_side_houses#publish'
      put 'complete', to: 'country_side_houses#complete'
      put 'return_to_publish', to: 'country_side_houses#return_to_publish'
    end
  end
  resources :commercial_premises do
    collection do
      put 'remove_from_work', to: 'commercial_premises#remove_from_work'
      put 'publish', to: 'commercial_premises#publish'
      put 'complete', to: 'commercial_premises#complete'
      put 'return_to_publish', to: 'commercial_premises#return_to_publish'
    end
  end
  resources :flats do
    collection do
      put 'remove_from_work', to: 'flats#remove_from_work'
      put 'publish', to: 'flats#publish'
      put 'complete', to: 'flats#complete'
      put 'return_to_publish', to: 'flats#return_to_publish'
    end
  end
  resources :cities do
    resources :streets
    resources :districts do
      resources :streets
    end
  end
  resources :streets
  resources :districts
  resources :roles
  resources :user
  put 'lock_user', to: 'user#lock_user'
  put 'unlock_user', to: 'user#unlock_user'
  devise_for :users, controllers: { 
    omniauth_callbacks: 'omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations' }
end

app/models/flat.rb
# == Schema Information
#
# Table name: flats
#
#  id                   :bigint           not null, primary key
#  celling_height       :decimal(, )
#  floor                :integer
#  kitchen_area         :decimal(, )
#  living_area          :decimal(, )
#  rooms_count          :integer
#  total_area           :decimal(, )
#  year_of_construction :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  renovation_id        :bigint           not null
#  wall_material_id     :bigint           not null
#
# Indexes
#
#  index_flats_on_renovation_id     (renovation_id)
#  index_flats_on_wall_material_id  (wall_material_id)
#
# Foreign Keys
#
#  fk_rails_...  (renovation_id => renovations.id)
#  fk_rails_...  (wall_material_id => wall_materials.id)
#
class Flat < ApplicationRecord
  belongs_to :renovation
  belongs_to :wall_material
  has_one :lot, as: :lotable, dependent: :destroy
  accepts_nested_attributes_for :lot
  delegate :title, :description, :price, to: :lot

  validates :celling_height, inclusion: { in: 1.80..5.0 }
  validates :floor, numericality: { only_integer: true }, inclusion: { in: 1..34 }
  validates :kitchen_area, inclusion: { in: 2.0..100.0 }
  validates :living_area, inclusion: { in: 2.0..100.0 }
  validates :rooms_count, numericality: { only_integer: true }, inclusion: { in: 1..40 }
  validates :total_area, inclusion: { in: 2.0..1000.0 }
  validates :year_of_construction, numericality: { only_integer: true }, inclusion: { in: 1900..2022 }

  scope :with_celling_height, ->(celling_height) { where(celling_height: celling_height) }
  scope :with_floor, ->(floor) { where(floor: floor) }
  scope :with_kitchen_area, ->(kitchen_area) { where(kitchen_area: kitchen_area) }
  scope :with_living_area, ->(living_area) { where(living_area: living_area) }
  scope :with_rooms_count, ->(rooms_count) { where(rooms_count: rooms_count) }
  scope :with_total_area, ->(total_area) { where(total_area: total_area) }
  scope :with_year_of_construction, ->(year_of_construction) { where(year_of_construction: year_of_construction) }
  scope :with_renovation_id, ->(renovation_id) { where(renovation_id: renovation_id) }
  scope :with_wall_material_id, ->(wall_material_id) { where(wall_material_id: wall_material_id) }
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  include Authenticated
  before_action :set_flat, only: %i[show edit update destroy remove_from_work publish complete return_to_publish]

  # GET /flats or /flats.json
  def index
    @flats = Flats::GetInteractor.new.call
    authorize @flats
    respond_to do |format|
      format.html
      format.json { render json: FlatDatatable.new(params, view_context: view_context, flats: @flats) }
    end
  end

  # GET /flats/1 or /flats/1.json
  def show
    authorize @flat
  end

  # GET /flats/new
  def new
    @flat = Flat.new
    @flat.build_lot
    @flat.lot.build_address
    authorize @flat
  end

  # GET /flats/1/edit
  def edit
    authorize @flat
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)
    authorize @flat
    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: 'Flat was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    authorize @flat
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: 'Flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy
    authorize @flat
    respond_to do |format|
      format.html { redirect_to flats_url, notice: 'Flat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_from_work
    authorize @flat
    @flat.lot.remove_from_work
    @flat.save
  end

  def publish
    authorize @flat
    @flat.lot.publish
    @flat.save
  end

  def complete
    authorize @flat
    @flat.lot.complete
    @flat.save
  end

  def return_to_publish
    authorize @flat
    @flat.lot.return_to_publish
    @flat.save
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_flat
    @flat = Flat.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flat_params
    params.require(:flat).permit(:rooms_count, :floor, :year_of_construction, :celling_height, :total_area,
                                 :living_area, :kitchen_area, :renovation_id, :wall_material_id,
                                 lot_attributes: [:id, :title, :description, :price, :client_id, :deal_type_id, { address_attributes: %i[id building description street_id] }, { images: [] }])
  end
end

app/views/flats/_form.html.erb
<% presenter = FlatPresenter.new %>
<div class="container" style="width: 600px;">
  <% if current_user.role.can_edit_lot %>
    <div class="field mb-3">
      <h5>State: <%= @flat&.lot&.state %></h5>
    </div>

    <% if @flat&.lot&.state == 'published' %>
      <%= button_to "Remove from work", remove_from_work_flats_path(id: @flat.id), method: :put, class: "btn btn-outline-danger mb-3" %>
      <%= button_to "Complete", complete_flats_path(id: @flat.id), method: :put, class: "btn btn-outline-success mb-3" %>
    <% elsif @flat&.lot&.state == 'not_started' %>
      <%= button_to "Publish", publish_flats_path(id: @flat.id), method: :put, class: "btn btn-outline-success mb-3" %>
    <% else %>
      <%= button_to "Return to publish", return_to_publish_flats_path(id: @flat.id), method: :put, class: "btn btn-outline-danger mb-3" %>
    <% end %>
  <% end %>

  <%= form_for @flat do |f| %>
  <% if @flat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flat.errors.count, "error") %> prohibited this flat from being saved:</h2>

      <ul>
        <% @flat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= f.label :renovation_id %>
    <%= f.collection_select :renovation_id, presenter.ordered_renovations, :id, :name %>
  </div>

  <div class="field mb-3">
    <%= f.label :rooms_count %>
    <%= f.number_field :rooms_count, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= f.label :floor %>
    <%= f.number_field :floor, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= f.label :wall_material_id %>
    <%= f.collection_select :wall_material_id, presenter.ordered_wall_materials, :id, :name %>
  </div>

  <div class="field mb-3">
    <%= f.label :kitchen_area %>
    <%= f.text_field :kitchen_area, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= f.label :living_area %>
    <%= f.text_field :living_area, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= f.label :total_area %>
    <%= f.text_field :total_area, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= f.label :celling_height %>
    <%= f.text_field :celling_height, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= f.label :year_of_construction %>
    <%= f.number_field :year_of_construction, class: "form-control" %>
  </div>

  <%= f.fields_for :lot do |lot| %>
    <div class="field mb-3">
      <%= lot.label :images %></br>
      <% if !@flat.lot.nil? %>
        <% if @flat.lot.images.attached? %>
          <% @flat.lot.images.each do |image| %>
            <%= image_tag image, size: '200', class: 'mb-3' %>
          <% end %>
        <% end %>
      <% end %>
      <%= lot.file_field :images, multiple: true, type: "file", class: "form-control" %>
    </div>

    <div class="field mb-3">
      <%= lot.label :title %>
      <%= lot.text_field :title, class: "form-control" %>
    </div>

    <div class="field mb-3">
      <%= lot.label :description %>
      <%= lot.text_area :description, class: "form-control" %>
    </div>

    <div class="field mb-3">
      <%= lot.label :price %>
      <%= lot.number_field :price, class: "form-control" %>
    </div>

    <div class="field">
      <%= lot.hidden_field :client_id, value: current_user.id %>
    </div>

    <div class="field mb-3">
      <%= lot.label :deal_type_id %>
      <%= lot.collection_select :deal_type_id, presenter.ordered_deal_types, :id, :name %>
    </div>

    <%= lot.fields_for :address do |address| %>
      <div class="field mb-3">
        <%= address.label :building %>
        <%= address.number_field :building, class: "form-control" %>
      </div>

      <div class="field mb-3">
        <%= address.label :description %>
        <%= address.text_area :description, class: "form-control" %>
      </div>

      <div class="field mb-3">
        <%= address.label :street_id %>
        <%= address.collection_select :street_id, presenter.ordered_streets, :id, :name %>
      </div>
    <% end %>
  <% end %>

  <div class="actions mb-2 d-grid gap-2 col-6 mx-auto">
    <%= f.submit 'Save', class:"btn btn-outline-success" %>
  </div>
<% end %>
</div>

app/views/flats/edit.html.erb
<div class="mx-auto" style="width: 300px;">
  <h1>Editing Flat</h1>
</div>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat, class: "btn btn-warning" %>
<%= link_to 'Back', flats_path, class: "btn btn-danger" %>

app/views/flats/index.html.erb
<div class="mx-auto" style="width: 200px;">
  <h1>Flats</h1>
</div>

<table class="table table-striped table-bordered table-hover" style="width:100%" id="flats-datatable", data-source="<%= flats_path(format: :json) %>">
  <thead>
    <tr style="background-color: #C8EEFF;">
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Deal type</th>
      <th>City</th>
      <th>District</th>
      <th>Street</th>
      <th>Building</th>
      <th>Address description</th>
      <th>Renovation</th>
      <th>Rooms count</th>
      <th>Floor</th>
      <th>Celling height</th>
      <th>Total area</th>
      <th>Living area</th>
      <th>Kitchen area</th>
      <th>Year of construction</th>
      <th>Wall material</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<script>
  jQuery(document).ready(function() {
  $('#flats-datatable').dataTable({
    "processing": true,
    "serverSide": true,
    "ajax": {
      "url": $('#flats-datatable').data('source')
    },
    "pagingType": "full_numbers",
    "columns": [
      {"data": "title"},
      {"data": "description"},
      {"data": "price"},
      {"data": "deal_type"},
      {"data": "city"},
      {"data": "district"},
      {"data": "street"},
      {"data": "building"},
      {"data": "address_description"},
      {"data": "renovation_id"},
      {"data": "rooms_count"},
      {"data": "floor"},
      {"data": "celling_height"},
      {"data": "total_area"},
      {"data": "living_area"},
      {"data": "kitchen_area"},
      {"data": "year_of_construction"},
      {"data": "wall_material_id"},
      {"data": "actions"}
    ]
  });
});
</script>

<%= link_to 'New Flat', new_flat_path, class: "btn btn-outline-info" %>

app/views/flats/new.html.erb
<div class="mx-auto" style="width: 200px;">
  <h1>New Flat</h1>
</div>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path, class: "btn btn-danger" %>

app/views/flats/show.html.erb
<p style="text-align: center;">
  <% if @flat.lot.images.attached? %>
    <% @flat.lot.images.each do |image| %>
      <%= image_tag image.variant(resize_to_limit: [250, 250]).processed %>
    <% end %>
  <% end %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>State:</strong>
  <%= @flat.lot.state %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Title:</strong>
  <%= @flat.lot.title %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Description:</strong>
  <%= @flat.lot.description %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Price:</strong>
  <%= @flat.lot.price %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Deal type:</strong>
  <%= @flat.lot.deal_type.name %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>City:</strong>
  <%= @flat.lot.address.street.district.city.name %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>District:</strong>
  <%= @flat.lot.address.street.district.name %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Street:</strong>
  <%= @flat.lot.address.street.name %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Building:</strong>
  <%= @flat.lot.address.building %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Address description:</strong>
  <%= @flat.lot.address.description %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Renovation:</strong>
  <%= @flat.renovation.name %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Rooms count:</strong>
  <%= @flat.rooms_count %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Floor:</strong>
  <%= @flat.floor %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Wall material:</strong>
  <%= @flat.wall_material.name %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Kitchen area:</strong>
  <%= @flat.kitchen_area %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Living area:</strong>
  <%= @flat.living_area %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Total area:</strong>
  <%= @flat.total_area %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Celling height:</strong>
  <%= @flat.celling_height %>
</p>

<p style="text-align: center; font-size: 20px">
  <strong>Year of construction:</strong>
  <%= @flat.year_of_construction %>
</p>

<% if current_user.role.can_edit_lot %>
  <p style="text-align: center; font-size: 20px">
    <strong>Asigner:</strong>
    <% if @flat.lot.asigner.nil? %>
      <%= 'Asigner not match' %>
    <% else %>
      <%= @flat.lot.asigner.full_name %>
    <% end %>
  </p>

  <p style="text-align: center; font-size: 20px">
    <strong>Asignee:</strong>
    <% if @flat.lot.asignee.nil? %>
      <%= 'Asignee not match' %>
    <% else %>
      <%= @flat.lot.asignee.full_name %>
    <% end %>
  </p>

  <p style="text-align: center; font-size: 20px">
    <strong>Client:</strong>
    <% if @flat.lot.client.nil? %>
      <%= 'Client not match' %>
    <% else %>
      <%= @flat.lot.client.full_name %>
    <% end %>
  </p>

  <div class="actions mb-2 d-grid gap-2 col-1 mx-auto">
    <%= link_to 'Edit', edit_flat_path(@flat), class: "btn btn-warning" %>
  </div>
<% end %>

<div class="actions mb-2 d-grid gap-2 col-1 mx-auto">
  <%= link_to 'Back', flats_path, class: "btn btn-danger" %>
</div>