config/routes.rb
# == Route Map
#
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root to: 'home#index'
  get 'flats_catalog', to: 'flats_catalog#index'
  get 'country_side_houses_catalog', to: 'country_side_houses_catalog#index'
  get 'commercial_premises_catalog', to: 'commercial_premises_catalog#index'
  get 'admin_panel', to: 'admin_panel#index'
  scope '/reports' do
    get 'users-count', to: 'reports#users_count'
    post 'users_count_report', to: 'reports#users_count_report'
    get 'clients-count', to: 'reports#clients_count'
    post 'clients_count_report', to: 'reports#clients_count_report'
    get 'realtors-count', to: 'reports#realtors_count'
    post 'realtors_count_report', to: 'reports#realtors_count_report'
    get 'locked-users-count', to: 'reports#locked_users_count'
    post 'locked_users_count_report', to: 'reports#locked_users_count_report'
    get 'lots-count', to: 'reports#lots_count'
    post 'lots_count_report', to: 'reports#lots_count_report'
    get 'commercial-premises-count', to: 'reports#commercial_premises_count'
    post 'commercial_premises_count_report', to: 'reports#commercial_premises_count_report'
    get 'country-side-houses-count', to: 'reports#country_side_houses_count'
    post 'country_side_houses_count_report', to: 'reports#country_side_houses_count_report'
    get 'flats-count', to: 'reports#flats_count'
    post 'flats_count_report', to: 'reports#flats_count_report'
    get 'not-started-lots-count', to: 'reports#not_started_lots_count'
    post 'not_started_lots_count_report', to: 'reports#not_started_lots_count_report'
    get 'published-lots-count', to: 'reports#published_lots_count'
    post 'published_lots_count_report', to: 'reports#published_lots_count_report'
    get 'completed-lots-count', to: 'reports#completed_lots_count'
    post 'completed_lots_count_report', to: 'reports#completed_lots_count_report'
  end
  resources :ordering
  resources :deal_types
  resources :countries
  resources :property_types
  resources :ready_states
  resources :country_side_house_kinds
  resources :commercial_premises_kinds
  resources :renovations
  resources :wall_materials
  resources :lots
  resources :country_side_houses do
    collection do
      put 'remove_from_work', to: 'country_side_houses#remove_from_work'
      put 'publish', to: 'country_side_houses#publish'
      put 'complete', to: 'country_side_houses#complete'
      put 'return_to_publish', to: 'country_side_houses#return_to_publish'
    end
  end
  resources :commercial_premises do
    collection do
      put 'remove_from_work', to: 'commercial_premises#remove_from_work'
      put 'publish', to: 'commercial_premises#publish'
      put 'complete', to: 'commercial_premises#complete'
      put 'return_to_publish', to: 'commercial_premises#return_to_publish'
    end
  end
  resources :flats do
    collection do
      put 'remove_from_work', to: 'flats#remove_from_work'
      put 'publish', to: 'flats#publish'
      put 'complete', to: 'flats#complete'
      put 'return_to_publish', to: 'flats#return_to_publish'
    end
  end
  resources :cities do
    resources :streets
    resources :districts do
      resources :streets
    end
  end
  resources :streets
  resources :districts
  resources :roles
  resources :user
  put 'lock_user', to: 'user#lock_user'
  put 'unlock_user', to: 'user#unlock_user'
  devise_for :users, controllers: { 
    omniauth_callbacks: 'omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations' }
end

app/models/renovation.rb
# == Schema Information
#
# Table name: renovations
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Renovation < ApplicationRecord
  has_one :flat, dependent: :nullify

  validates :name, length: { in: 3..30 }, format: { with: /\A[a-zA-Z ]+\z/ }

  scope :with_name, ->(name) { where(name: name) }
end

app/controllers/renovations_controller.rb
class RenovationsController < ApplicationController
  include Authenticated
  before_action :set_renovation, only: %i[show edit update destroy]

  # GET /renovations or /renovations.json
  def index
    @renovations = Renovation.all
    authorize @renovations
    respond_to do |format|
      format.html
      format.json { render json: RenovationDatatable.new(params, view_context: view_context, renovations: @renovations) }
    end
  end

  # GET /renovations/1 or /renovations/1.json
  def show
    authorize @renovation
  end

  # GET /renovations/new
  def new
    @renovation = Renovation.new
    authorize @renovation
  end

  # GET /renovations/1/edit
  def edit
    authorize @renovation
  end

  # POST /renovations or /renovations.json
  def create
    @renovation = Renovation.new(renovation_params)
    authorize @renovation
    respond_to do |format|
      if @renovation.save
        format.html { redirect_to renovation_url(@renovation), notice: 'Renovation was successfully created.' }
        format.json { render :show, status: :created, location: @renovation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @renovation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /renovations/1 or /renovations/1.json
  def update
    authorize @renovation
    respond_to do |format|
      if @renovation.update(renovation_params)
        format.html { redirect_to renovation_url(@renovation), notice: 'Renovation was successfully updated.' }
        format.json { render :show, status: :ok, location: @renovation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @renovation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renovations/1 or /renovations/1.json
  def destroy
    @renovation.destroy
    authorize @renovation
    respond_to do |format|
      format.html { redirect_to renovations_url, notice: 'Renovation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_renovation
    @renovation = Renovation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def renovation_params
    params.require(:renovation).permit(:name)
  end
end

app/views/renovations/_form.html.erb
<div class="container" style="width: 600px;">
<%= form_with(model: renovation) do |form| %>
  <% if renovation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(renovation.errors.count, "error") %> prohibited this renovation from being saved:</h2>

      <ul>
        <% renovation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions mb-2 d-grid gap-2 col-6 mx-auto">
    <%= form.submit 'Save', class:"btn btn-outline-success" %>
  </div>
<% end %>
</div>

app/views/renovations/edit.html.erb
<div class="mx-auto" style="width: 400px;">
  <h1>Editing Renovation</h1>
</div>

<%= render 'form', renovation: @renovation %>

<%= link_to 'Show', @renovation, class: "btn btn-warning" %>
<%= link_to 'Back', renovations_path, class: "btn btn-danger" %>

app/views/renovations/index.html.erb
<div class="mx-auto" style="width: 300px;">
  <h1>Renovations</h1>
</div>

<table class="table table-striped table-bordered table-hover" style="width:100%" id="renovations-datatable", data-source="<%= renovations_path(format: :json) %>">
  <thead>
    <tr style="background-color: #C8EEFF;">
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<script>
  jQuery(document).ready(function() {
  $('#renovations-datatable').dataTable({
    "processing": true,
    "serverSide": true,
    "ajax": {
      "url": $('#renovations-datatable').data('source')
    },
    "pagingType": "full_numbers",
    "columns": [
      {"data": "name"},
      {"data": "actions"}
    ]
  });
});
</script>

<%= link_to 'New Renovation', new_renovation_path, class: "btn btn-outline-info" %>

app/views/renovations/new.html.erb
<div class="mx-auto" style="width: 400px;">
  <h1>New Renovation</h1>
</div>

<%= render 'form', renovation: @renovation %>

<%= link_to 'Back', renovations_path, class: "btn btn-danger" %>

app/views/renovations/show.html.erb
<p style="text-align: center; font-size: 20px">
  <strong>Name:</strong>
  <%= @renovation.name %>
</p>

<%= link_to 'Edit', edit_renovation_path(@renovation), class: "btn btn-warning" %>
<%= link_to 'Back', renovations_path, class: "btn btn-danger" %>