config/routes.rb
# == Route Map
#
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  root to: 'home#index'
  get 'flats_catalog', to: 'flats_catalog#index'
  get 'country_side_houses_catalog', to: 'country_side_houses_catalog#index'
  get 'commercial_premises_catalog', to: 'commercial_premises_catalog#index'
  get 'admin_panel', to: 'admin_panel#index'
  scope '/reports' do
    get 'users-count', to: 'reports#users_count'
    post 'users_count_report', to: 'reports#users_count_report'
    get 'clients-count', to: 'reports#clients_count'
    post 'clients_count_report', to: 'reports#clients_count_report'
    get 'realtors-count', to: 'reports#realtors_count'
    post 'realtors_count_report', to: 'reports#realtors_count_report'
    get 'locked-users-count', to: 'reports#locked_users_count'
    post 'locked_users_count_report', to: 'reports#locked_users_count_report'
    get 'lots-count', to: 'reports#lots_count'
    post 'lots_count_report', to: 'reports#lots_count_report'
    get 'commercial-premises-count', to: 'reports#commercial_premises_count'
    post 'commercial_premises_count_report', to: 'reports#commercial_premises_count_report'
    get 'country-side-houses-count', to: 'reports#country_side_houses_count'
    post 'country_side_houses_count_report', to: 'reports#country_side_houses_count_report'
    get 'flats-count', to: 'reports#flats_count'
    post 'flats_count_report', to: 'reports#flats_count_report'
    get 'not-started-lots-count', to: 'reports#not_started_lots_count'
    post 'not_started_lots_count_report', to: 'reports#not_started_lots_count_report'
    get 'published-lots-count', to: 'reports#published_lots_count'
    post 'published_lots_count_report', to: 'reports#published_lots_count_report'
    get 'completed-lots-count', to: 'reports#completed_lots_count'
    post 'completed_lots_count_report', to: 'reports#completed_lots_count_report'
  end
  resources :ordering
  resources :deal_types
  resources :countries
  resources :property_types
  resources :ready_states
  resources :country_side_house_kinds
  resources :commercial_premises_kinds
  resources :renovations
  resources :wall_materials
  resources :lots
  resources :country_side_houses do
    collection do
      put 'remove_from_work', to: 'country_side_houses#remove_from_work'
      put 'publish', to: 'country_side_houses#publish'
      put 'complete', to: 'country_side_houses#complete'
      put 'return_to_publish', to: 'country_side_houses#return_to_publish'
    end
  end
  resources :commercial_premises do
    collection do
      put 'remove_from_work', to: 'commercial_premises#remove_from_work'
      put 'publish', to: 'commercial_premises#publish'
      put 'complete', to: 'commercial_premises#complete'
      put 'return_to_publish', to: 'commercial_premises#return_to_publish'
    end
  end
  resources :flats do
    collection do
      put 'remove_from_work', to: 'flats#remove_from_work'
      put 'publish', to: 'flats#publish'
      put 'complete', to: 'flats#complete'
      put 'return_to_publish', to: 'flats#return_to_publish'
    end
  end
  resources :cities do
    resources :streets
    resources :districts do
      resources :streets
    end
  end
  resources :streets
  resources :districts
  resources :roles
  resources :user
  put 'lock_user', to: 'user#lock_user'
  put 'unlock_user', to: 'user#unlock_user'
  devise_for :users, controllers: { 
    omniauth_callbacks: 'omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations' }
end

app/models/country_side_house_kind.rb
# == Schema Information
#
# Table name: country_side_house_kinds
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CountrySideHouseKind < ApplicationRecord
  has_one :country_side_house, dependent: :nullify

  validates :name, length: { in: 3..30 }, format: { with: /\A[a-zA-Z ]+\z/ }

  scope :with_name, ->(name) { where(name: name) }
end

app/controllers/country_side_house_kinds_controller.rb
class CountrySideHouseKindsController < ApplicationController
  include Authenticated
  before_action :set_country_side_house_kind, only: %i[show edit update destroy]

  # GET /country_side_house_kinds or /country_side_house_kinds.json
  def index
    @country_side_house_kinds = CountrySideHouseKind.all
    authorize @country_side_house_kinds
    respond_to do |format|
      format.html
      format.json { render json: CountrySideHouseKindDatatable.new(params, view_context: view_context, country_side_house_kinds: @country_side_house_kinds) }
    end
  end

  # GET /country_side_house_kinds/1 or /country_side_house_kinds/1.json
  def show
    authorize @country_side_house_kind
  end

  # GET /country_side_house_kinds/new
  def new
    @country_side_house_kind = CountrySideHouseKind.new
    authorize @country_side_house_kind
  end

  # GET /country_side_house_kinds/1/edit
  def edit
    authorize @country_side_house_kind
  end

  # POST /country_side_house_kinds or /country_side_house_kinds.json
  def create
    @country_side_house_kind = CountrySideHouseKind.new(country_side_house_kind_params)
    authorize @country_side_house_kind
    respond_to do |format|
      if @country_side_house_kind.save
        format.html do
          redirect_to country_side_house_kind_url(@country_side_house_kind),
                      notice: 'Country side house kind was successfully created.'
        end
        format.json { render :show, status: :created, location: @country_side_house_kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country_side_house_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /country_side_house_kinds/1 or /country_side_house_kinds/1.json
  def update
    authorize @country_side_house_kind
    respond_to do |format|
      if @country_side_house_kind.update(country_side_house_kind_params)
        format.html do
          redirect_to country_side_house_kind_url(@country_side_house_kind),
                      notice: 'Country side house kind was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @country_side_house_kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country_side_house_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /country_side_house_kinds/1 or /country_side_house_kinds/1.json
  def destroy
    @country_side_house_kind.destroy
    authorize @country_side_house_kind
    respond_to do |format|
      format.html do
        redirect_to country_side_house_kinds_url, notice: 'Country side house kind was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_country_side_house_kind
    @country_side_house_kind = CountrySideHouseKind.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def country_side_house_kind_params
    params.require(:country_side_house_kind).permit(:name)
  end
end

app/views/country_side_house_kinds/_form.html.erb
<div class="container" style="width: 600px;">
<%= form_with(model: country_side_house_kind) do |form| %>
  <% if country_side_house_kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country_side_house_kind.errors.count, "error") %> prohibited this country_side_house_kind from being saved:</h2>

      <ul>
        <% country_side_house_kind.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions mb-2 d-grid gap-2 col-6 mx-auto">
    <%= form.submit 'Save', class:"btn btn-outline-success" %>
  </div>
<% end %>
</div>

app/views/country_side_house_kinds/edit.html.erb
<div class="mx-auto" style="width: 700px;">
  <h1>Editing Country Side House Kind</h1>
</div>

<%= render 'form', country_side_house_kind: @country_side_house_kind %>

<%= link_to 'Show', @country_side_house_kind, class: "btn btn-warning" %>
<%= link_to 'Back', country_side_house_kinds_path, class: "btn btn-danger" %>

app/views/country_side_house_kinds/index.html.erb
<div class="mx-auto" style="width: 600px;">
  <h1>Country Side House Kinds</h1>
</div>

<table class="table table-striped table-bordered table-hover" style="width:100%" id="country_side_house_kinds-datatable", data-source="<%= country_side_house_kinds_path(format: :json) %>">
  <thead>
    <tr style="background-color: #C8EEFF;">
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

<script>
  jQuery(document).ready(function() {
  $('#country_side_house_kinds-datatable').dataTable({
    "processing": true,
    "serverSide": true,
    "ajax": {
      "url": $('#country_side_house_kinds-datatable').data('source')
    },
    "pagingType": "full_numbers",
    "columns": [
      {"data": "name"},
      {"data": "actions"}
    ]
  });
});
</script>

<%= link_to 'New Country Side House Kind', new_country_side_house_kind_path, class: "btn btn-outline-info" %>

app/views/country_side_house_kinds/new.html.erb
<div class="mx-auto" style="width: 600px;">
  <h1>New Country Side House Kind</h1>
</div>

<%= render 'form', country_side_house_kind: @country_side_house_kind %>

<%= link_to 'Back', country_side_house_kinds_path, class: "btn btn-danger" %>

app/views/country_side_house_kinds/show.html.erb
<p style="text-align: center; font-size: 20px">
  <strong>Name:</strong>
  <%= @country_side_house_kind.name %>
</p>

<%= link_to 'Edit', edit_country_side_house_kind_path(@country_side_house_kind), class: "btn btn-warning" %>
<%= link_to 'Back', country_side_house_kinds_path, class: "btn btn-danger" %>